version: '2'

services:
  postgres:
    build:
      context: databaes/
    env_file: molecular-playground.env
    networks:
      - database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  msusers:
    build: ms-users/
    env_file: molecular-playground.env
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  mslogin:
    build: ms-login/
    env_file: molecular-playground.env
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  msschedule:
    build: ms-schedule/
    env_file: molecular-playground.env
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  msemail:
    build: ms-email/
    env_file: molecular-playground.env
    command: npm start

  msmolecules:
    build: ms-molecules/
    env_file: molecular-playground.env
    networks:
      - default
      - database
    volumes:
      - ../molecules:/src/public
    depends_on:
      - postgres
    command: npm start

  gateway:
    build: gateway/
    env_file: molecular-playground.env
    ports:
      - "8000:8000"
    command: npm start

  frontend:
    build: frontend/
    env_file: molecular-playground.env
    ports:
      - "80:3000"
    command: npm start

networks:
  database:
    driver: bridge

volumes:
  postgres-data:
    driver: local
