version: '2'

services:
  postgres:
    build:
      context: databaes/
    environment:
      POSTGRES_PASSWORD: dankmemes
    networks:
      - database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  msusers:
    build: ms-users/
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  msusersauth:
    build: ms-users-auth/
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  mslogin:
    build: ms-login/
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  msschedule:
    build: ms-schedule/
    networks:
      - default
      - database
    depends_on:
      - postgres
    command: npm start

  msemail:
    build: ms-email/
    command: npm start

  gateway:
    build: gateway/
    ports:
      - "8000:8000"
    command: npm start

networks:
  database:
    driver: bridge

volumes:
  postgres-data:
    driver: local
